/* 
 * Sweep API
 *
 * API definitions for the Sweep server/dashboard.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@avinium.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Sweep.Client;
using Sweep.Api;
using Sweep.Model;

namespace Sweep.Test
{
    /// <summary>
    ///  Class for testing EventApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EventApiTests : IDisposable
    {
        private EventApi instance;

        public EventApiTests()
        {
            instance = new EventApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EventApi
            //Assert.IsType(typeof(EventApi), instance, "instance is a EventApi");
        }

        
        /// <summary>
        /// Test AddEvent
        /// </summary>
        [Fact]
        public void AddEventTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EventRequestBody eventRequestBody = null;
            //string apiKey = null;
            //instance.AddEvent(eventRequestBody, apiKey);
            
        }
        
        /// <summary>
        /// Test GetEventById
        /// </summary>
        [Fact]
        public void GetEventByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string eventId = null;
            //var response = instance.GetEventById(eventId);
            //Assert.IsType<Event> (response, "response is Event");
        }
        
        /// <summary>
        /// Test ListEvents
        /// </summary>
        [Fact]
        public void ListEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? withActions = null;
            //DateTime? startDate = null;
            //DateTime? endDate = null;
            //var response = instance.ListEvents(withActions, startDate, endDate);
            //Assert.IsType<List<Event>> (response, "response is List<Event>");
        }
        
    }

}
