/* 
 * Sweep API
 *
 * API definitions for the Sweep server/dashboard.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@avinium.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Sweep.Client;
using Sweep.Api;
using Sweep.Model;

namespace Sweep.Test
{
    /// <summary>
    ///  Class for testing OrganizationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OrganizationApiTests : IDisposable
    {
        private OrganizationApi instance;

        public OrganizationApiTests()
        {
            instance = new OrganizationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganizationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OrganizationApi
            //Assert.IsType(typeof(OrganizationApi), instance, "instance is a OrganizationApi");
        }

        
        /// <summary>
        /// Test GetOrganizationInfo
        /// </summary>
        [Fact]
        public void GetOrganizationInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetOrganizationInfo();
            //Assert.IsType<Organization> (response, "response is Organization");
        }
        
    }

}
