/* 
 * Sweep API
 *
 * API definitions for the Sweep server/dashboard.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@avinium.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sweep.Api;
using Sweep.Model;
using Sweep.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sweep.Test
{
    /// <summary>
    ///  Class for testing EventRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventRequestBody
        //private EventRequestBody instance;

        public EventRequestBodyTests()
        {
            // TODO uncomment below to create an instance of EventRequestBody
            //instance = new EventRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventRequestBody
        /// </summary>
        [Fact]
        public void EventRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventRequestBody
            //Assert.IsInstanceOfType<EventRequestBody> (instance, "variable 'instance' is a EventRequestBody");
        }


        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Fact]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }

    }

}
