/* 
 * Sweep API
 *
 * API definitions for the Sweep server/dashboard.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@avinium.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sweep.Api;
using Sweep.Model;
using Sweep.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sweep.Test
{
    /// <summary>
    ///  Class for testing ListenerTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListenerTemplateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListenerTemplate
        //private ListenerTemplate instance;

        public ListenerTemplateTests()
        {
            // TODO uncomment below to create an instance of ListenerTemplate
            //instance = new ListenerTemplate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListenerTemplate
        /// </summary>
        [Fact]
        public void ListenerTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListenerTemplate
            //Assert.IsInstanceOfType<ListenerTemplate> (instance, "variable 'instance' is a ListenerTemplate");
        }


        /// <summary>
        /// Test the property 'ListenerId'
        /// </summary>
        [Fact]
        public void ListenerIdTest()
        {
            // TODO unit test for the property 'ListenerId'
        }
        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }
        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }

    }

}
