/* 
 * Sweep API
 *
 * API definitions for the Sweep server/dashboard.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@avinium.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sweep.Api;
using Sweep.Model;
using Sweep.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sweep.Test
{
    /// <summary>
    ///  Class for testing Listener
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListenerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Listener
        //private Listener instance;

        public ListenerTests()
        {
            // TODO uncomment below to create an instance of Listener
            //instance = new Listener();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Listener
        /// </summary>
        [Fact]
        public void ListenerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Listener
            //Assert.IsInstanceOfType<Listener> (instance, "variable 'instance' is a Listener");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Fact]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'EventParams'
        /// </summary>
        [Fact]
        public void EventParamsTest()
        {
            // TODO unit test for the property 'EventParams'
        }
        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
        /// <summary>
        /// Test the property 'TriggerEvent'
        /// </summary>
        [Fact]
        public void TriggerEventTest()
        {
            // TODO unit test for the property 'TriggerEvent'
        }
        /// <summary>
        /// Test the property 'TriggerNumber'
        /// </summary>
        [Fact]
        public void TriggerNumberTest()
        {
            // TODO unit test for the property 'TriggerNumber'
        }
        /// <summary>
        /// Test the property 'TriggerPeriod'
        /// </summary>
        [Fact]
        public void TriggerPeriodTest()
        {
            // TODO unit test for the property 'TriggerPeriod'
        }
        /// <summary>
        /// Test the property 'TriggerMatch'
        /// </summary>
        [Fact]
        public void TriggerMatchTest()
        {
            // TODO unit test for the property 'TriggerMatch'
        }

    }

}
