/* 
 * Sweep API
 *
 * API definitions for the Sweep server/dashboard.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@avinium.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sweep.Api;
using Sweep.Model;
using Sweep.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sweep.Test
{
    /// <summary>
    ///  Class for testing Organization
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganizationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Organization
        //private Organization instance;

        public OrganizationTests()
        {
            // TODO uncomment below to create an instance of Organization
            //instance = new Organization();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Organization
        /// </summary>
        [Fact]
        public void OrganizationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Organization
            //Assert.IsInstanceOfType<Organization> (instance, "variable 'instance' is a Organization");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PrimaryApiKey'
        /// </summary>
        [Fact]
        public void PrimaryApiKeyTest()
        {
            // TODO unit test for the property 'PrimaryApiKey'
        }
        /// <summary>
        /// Test the property 'SecondaryApiKey'
        /// </summary>
        [Fact]
        public void SecondaryApiKeyTest()
        {
            // TODO unit test for the property 'SecondaryApiKey'
        }

    }

}
