/* 
 * Sweep API
 *
 * API definitions for the Sweep server/dashboard.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@avinium.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sweep.Api;
using Sweep.Model;
using Sweep.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sweep.Test
{
    /// <summary>
    ///  Class for testing RenderTemplateRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RenderTemplateRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RenderTemplateRequestBody
        //private RenderTemplateRequestBody instance;

        public RenderTemplateRequestBodyTests()
        {
            // TODO uncomment below to create an instance of RenderTemplateRequestBody
            //instance = new RenderTemplateRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenderTemplateRequestBody
        /// </summary>
        [Fact]
        public void RenderTemplateRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RenderTemplateRequestBody
            //Assert.IsInstanceOfType<RenderTemplateRequestBody> (instance, "variable 'instance' is a RenderTemplateRequestBody");
        }


        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }

    }

}
