/* 
 * Sweep API
 *
 * API definitions for the Sweep server/dashboard.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@avinium.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sweep.Api;
using Sweep.Model;
using Sweep.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sweep.Test
{
    /// <summary>
    ///  Class for testing UserRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserRequestBody
        //private UserRequestBody instance;

        public UserRequestBodyTests()
        {
            // TODO uncomment below to create an instance of UserRequestBody
            //instance = new UserRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserRequestBody
        /// </summary>
        [Fact]
        public void UserRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserRequestBody
            //Assert.IsInstanceOfType<UserRequestBody> (instance, "variable 'instance' is a UserRequestBody");
        }


        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
