/* 
 * Sweep API
 *
 * API definitions for the Sweep server/dashboard.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@avinium.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Sweep.Client.OpenAPIDateConverter;

namespace Sweep.Model
{
    /// <summary>
    /// Listener
    /// </summary>
    [DataContract]
    public partial class Listener :  IEquatable<Listener>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Listener" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Listener() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Listener" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="eventName">eventName (required).</param>
        /// <param name="eventParams">eventParams.</param>
        /// <param name="organizationId">organizationId (required).</param>
        /// <param name="triggerEvent">triggerEvent.</param>
        /// <param name="triggerNumber">triggerNumber.</param>
        /// <param name="triggerPeriod">triggerPeriod.</param>
        /// <param name="triggerMatch">triggerMatch.</param>
        public Listener(string id = default(string), string eventName = default(string), List<string> eventParams = default(List<string>), string organizationId = default(string), string triggerEvent = default(string), int triggerNumber = default(int), string triggerPeriod = default(string), string triggerMatch = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for Listener and cannot be null");
            }
            else
            {
                this.Id = id;
            }

            // to ensure "eventName" is required (not null)
            if (eventName == null)
            {
                throw new InvalidDataException("eventName is a required property for Listener and cannot be null");
            }
            else
            {
                this.EventName = eventName;
            }

            // to ensure "organizationId" is required (not null)
            if (organizationId == null)
            {
                throw new InvalidDataException("organizationId is a required property for Listener and cannot be null");
            }
            else
            {
                this.OrganizationId = organizationId;
            }

            this.EventParams = eventParams;
            this.TriggerEvent = triggerEvent;
            this.TriggerNumber = triggerNumber;
            this.TriggerPeriod = triggerPeriod;
            this.TriggerMatch = triggerMatch;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets EventName
        /// </summary>
        [DataMember(Name="eventName", EmitDefaultValue=false)]
        public string EventName { get; set; }

        /// <summary>
        /// Gets or Sets EventParams
        /// </summary>
        [DataMember(Name="eventParams", EmitDefaultValue=false)]
        public List<string> EventParams { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [DataMember(Name="organizationId", EmitDefaultValue=false)]
        public string OrganizationId { get; set; }

        /// <summary>
        /// Gets or Sets TriggerEvent
        /// </summary>
        [DataMember(Name="triggerEvent", EmitDefaultValue=false)]
        public string TriggerEvent { get; set; }

        /// <summary>
        /// Gets or Sets TriggerNumber
        /// </summary>
        [DataMember(Name="triggerNumber", EmitDefaultValue=false)]
        public int TriggerNumber { get; set; }

        /// <summary>
        /// Gets or Sets TriggerPeriod
        /// </summary>
        [DataMember(Name="triggerPeriod", EmitDefaultValue=false)]
        public string TriggerPeriod { get; set; }

        /// <summary>
        /// Gets or Sets TriggerMatch
        /// </summary>
        [DataMember(Name="triggerMatch", EmitDefaultValue=false)]
        public string TriggerMatch { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Listener {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  EventName: ").Append(EventName).Append("\n");
            sb.Append("  EventParams: ").Append(EventParams).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  TriggerEvent: ").Append(TriggerEvent).Append("\n");
            sb.Append("  TriggerNumber: ").Append(TriggerNumber).Append("\n");
            sb.Append("  TriggerPeriod: ").Append(TriggerPeriod).Append("\n");
            sb.Append("  TriggerMatch: ").Append(TriggerMatch).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Listener);
        }

        /// <summary>
        /// Returns true if Listener instances are equal
        /// </summary>
        /// <param name="input">Instance of Listener to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Listener input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.EventName == input.EventName ||
                    (this.EventName != null &&
                    this.EventName.Equals(input.EventName))
                ) && 
                (
                    this.EventParams == input.EventParams ||
                    this.EventParams != null &&
                    this.EventParams.SequenceEqual(input.EventParams)
                ) && 
                (
                    this.OrganizationId == input.OrganizationId ||
                    (this.OrganizationId != null &&
                    this.OrganizationId.Equals(input.OrganizationId))
                ) && 
                (
                    this.TriggerEvent == input.TriggerEvent ||
                    (this.TriggerEvent != null &&
                    this.TriggerEvent.Equals(input.TriggerEvent))
                ) && 
                (
                    this.TriggerNumber == input.TriggerNumber ||
                    (this.TriggerNumber != null &&
                    this.TriggerNumber.Equals(input.TriggerNumber))
                ) && 
                (
                    this.TriggerPeriod == input.TriggerPeriod ||
                    (this.TriggerPeriod != null &&
                    this.TriggerPeriod.Equals(input.TriggerPeriod))
                ) && 
                (
                    this.TriggerMatch == input.TriggerMatch ||
                    (this.TriggerMatch != null &&
                    this.TriggerMatch.Equals(input.TriggerMatch))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.EventName != null)
                    hashCode = hashCode * 59 + this.EventName.GetHashCode();
                if (this.EventParams != null)
                    hashCode = hashCode * 59 + this.EventParams.GetHashCode();
                if (this.OrganizationId != null)
                    hashCode = hashCode * 59 + this.OrganizationId.GetHashCode();
                if (this.TriggerEvent != null)
                    hashCode = hashCode * 59 + this.TriggerEvent.GetHashCode();
                if (this.TriggerNumber != null)
                    hashCode = hashCode * 59 + this.TriggerNumber.GetHashCode();
                if (this.TriggerPeriod != null)
                    hashCode = hashCode * 59 + this.TriggerPeriod.GetHashCode();
                if (this.TriggerMatch != null)
                    hashCode = hashCode * 59 + this.TriggerMatch.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (string) maxLength
            if(this.Id != null && this.Id.Length > 36)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Id, length must be less than 36.", new [] { "Id" });
            }

            // Id (string) minLength
            if(this.Id != null && this.Id.Length < 36)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Id, length must be greater than 36.", new [] { "Id" });
            }

            yield break;
        }
    }

}
